### ISSUE TITLE
esdl2 on Windows, tracking

### ISSUE THREAD

**Issue by fire** [ninenines/esdl2#10]
Goal is to make esdl2 work on Windows.

Description of my attempts to get esdl2 working on windows.

**Comment by fire** [comment]
Something is causing my esdl2 nif to not  be loaded:

```elixir
iex(7)> :erlang.load_nif("c:/w/ex_bgfx/dep/sdl2/_build/dev/lib/esdl2/priv/SDL2", 0)      
{:error,
 {:bad_lib,
  'Failed to find library init function: \'The specified procedure could not be found.\''}}
iex(8)> :erlang.load_nif("c:/w/ex_bgfx/dep/sdl2/_build/dev/lib/esdl2/priv/esdl2", 0)     
{:error,
 {:load_failed,
  'Failed to load NIF library c:/w/ex_bgfx/dep/sdl2/_build/dev/lib/esdl2/priv/esdl2: \'The specified module could not be found.\''}}
```

https://drive.google.com/file/d/0B1AVSefkjf_LZUYybXNGZGZPUzg/view?usp=sharing

Here's a link to the project: 

* Requires SDL2_IMAGE_PATH and SDL2_PATH to be set
* Requires Visual Studio 2015
* Requires cmake

**Comment by fire** [comment]
Use commands like `mix compile` `mix compile.esdl2` and `iex -S mix compile --no-start --werl`.

**Comment by fire** [comment]
Notice that sdl2/deps/esdl2 is this repository.

**Comment by essen** [comment]
To load the NIF you should do `l(esdl2)`, not the command you're using there.

**Comment by fire** [comment]
```
iex(2)> l(:esdl2)
{:error, :on_load_failure}
iex(3)> 
09:45:16.195 [warn]  The on_load function for module esdl2 returned {:error,
 {:load_failed,
  'Failed to load NIF library c:/w/ex_bgfx/dep/sdl2/_build/dev/lib/esdl2/priv/esdl2: \'The specified module could not be found.\''}}
```

Weird

**Comment by essen** [comment]
What's the contents of the `c:/w/ex_bgfx/dep/sdl2/_build/dev/lib/esdl2/priv/esdl2` directory?

**Comment by fire** [comment]
`dep/sdl2/_build/dev/lib/esdl2/priv/esdl2.dll` and other files as seen the zip.

**Comment by brainstormi** [comment]
Cool!... How were you able to compile esdl2 in windows in a first place?.
From what I see, nif_helpers.c has a dependecy on sys/queue.h library that it isn't available in Windows, only linux/BSD. Did you rewrite it using a portable library?.
Regards,

**Comment by essen** [comment]
He took an independent implementation from a library, forgot which one though. Anyway the queue implementation on Linux is basically just macros so it works everywhere.

**Comment by brainstormi** [comment]
excuse me... newbie here :) I'm using Msys2 environment to run erlang.mk build system in esdl2... Just running make the compilation fails complaining about the missing library, how could I fix it without "rewriting" nif_helpers?.

**Comment by essen** [comment]
Hey, I don't have all the details yet. I will look into it soon, maybe this week-end, I should have more time than last one. Right now it won't work but the sys/queue.h thing will be easy to fix. But that's not the only issue, and I don't think anyone got it working on Windows yet.

**Comment by fire** [comment]
Used `http://www.chriscalender.com/tag/sysqueue-h-found/` as the independent implementation of queue.h.

**Comment by brainstormi** [comment]
I tested with the queue.h implementation pointed and as essen preview it, I ended with your same error inside a msys2 environment trying to loading the nif: "The specified module could not be found", although esdl2.so is in the correct path.

**Comment by essen** [comment]
One reason for that is that we must build a DLL, not a SO. :-)

**Comment by brainstormi** [comment]
jajaja... yeah, msys2 is so linux i forgot it...

**Comment by brainstormi** [comment]
Done... and Runninnnnngggggg!!!
although it's not so fluent like running in linux or and old core2duo osx... lots of stuttering and micro-pauses... Not sure if it's windows drivers thing or a sdl2/nif issue.
In the same way than in osx, the bullet_engine demo crashes (well in this case it hungs) when it ends.

**Comment by essen** [comment]
Please post everything you did and/or PR. :-)

Same for OSX, I think I have a ticket for this but I might have closed it thinking it was fixed.

**Comment by brainstormi** [comment]
Too quick and dirty hacks for a PR, so I included here some quick steps,  expecting not to forget any:
1. Setup MSYS2 environment following erlang.mk instructions: https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/installation.asciidoc
2. Install dependecies (not sure if base-devel would be needed):
pacman -Ss mingw-w64-x86_64-gcc base-devel mingw-w64-x86_64-SDL2  mingw-w64-x86_64-SDL2_image
3. erlang.mk tries to use cc compiler... 
ln -s /mingw64/bin/gcc /mingw64/bin/cc
4. Clonning esdl2 repository:
git clone https://github.com/ninenines/esdl2.git
5. Adding queue.h implementation pointed by fire user to c_src and updating esdl2.c and nif_helpers.c to use it.
#include <sys/queue.h> => #include "queue.h"
6. Update Makefile to include erlang libs and headers:
CFLAGS += $(shell sdl2-config --cflags)  -I"/C/Program Files/erl7.1/usr/include"
# @todo -undefined dynamic_lookup on OSX?
LDLIBS += $(SDL2_LIBS) -lSDL2_image  -L"/C/Program Files/erl7.1/usr/lib"
7. make
8. this is good! :) 
    mv priv/esdl2.so priv/esdl2.dll
9. make bullet_engine


I don't have my OSX laptop here, I'll update it when possible...

**Comment by essen** [comment]
Wow. I'll try soon, I didn't expect it would work with gcc that easily.

**Comment by essen** [comment]
Thanks!!

**Comment by fire** [comment]
Erroring out with 

```
$  PKG_CONFIG_PATH=/mingw64/lib/pkgconfig/  make
 C      esdl2.c
/c/w/esdl2/c_src/esdl2.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright (c) 2014-2015, Loïc Hoguin <essen@ninenines.eu>
 ^
In file included from /c/w/esdl2/c_src/nif_helpers.h:18:0,
                 from /c/w/esdl2/c_src/esdl2.h:254,
                 from /c/w/esdl2/c_src/esdl2.c:15:
/c/Program Files/erl7.1/usr/include/erl_nif.h:100:26: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘ErlNifUInt64’
 typedef unsigned __int64 ErlNifUInt64;
                          ^
/c/Program Files/erl7.1/usr/include/erl_nif.h:101:9: error: unknown type name ‘__int64’
 typedef __int64 ErlNifSInt64;
         ^
/c/Program Files/erl7.1/usr/include/erl_nif_api_funcs.h:135:75: error: unknown type name ‘ErlNifUInt64’
 ERL_NIF_API_FUNC_DECL(int,enif_get_uint64,(ErlNifEnv*, ERL_NIF_TERM term, ErlNifUInt64* ip));
                                                                           ^
/c/Program Files/erl7.1/usr/include/erl_nif.h:231:72: note: in definition of macro ‘ERL_NIF_API_FUNC_DECL’
 #  define ERL_NIF_API_FUNC_DECL(RET_TYPE, NAME, ARGS) RET_TYPE (*NAME) ARGS
                                                                        ^
/c/Program Files/erl7.1/usr/include/erl_nif_api_funcs.h:137:66: error: unknown type name ‘ErlNifUInt64’
 ERL_NIF_API_FUNC_DECL(ERL_NIF_TERM,enif_make_uint64,(ErlNifEnv*, ErlNifUInt64));
                                                                  ^
/c/Program Files/erl7.1/usr/include/erl_nif.h:231:72: note: in definition of macro ‘ERL_NIF_API_FUNC_DECL’
 #  define ERL_NIF_API_FUNC_DECL(RET_TYPE, NAME, ARGS) RET_TYPE (*NAME) ARGS
                                                                        ^
erlang.mk:5585: recipe for target '/c/w/esdl2/c_src/esdl2.o' failed
make: *** [/c/w/esdl2/c_src/esdl2.o] Error 1
```

**Comment by brainstormi** [comment]
I think you missed to include erlang headers and libs...
You have to update Makefile CFLAGS and LDLIBS as below with the correct path to your erlang installation.
CFLAGS += $(shell sdl2-config --cflags) -I"/C/Program Files/erl7.1/usr/include"
LDLIBS += $(SDL2_LIBS) -lSDL2_image -L"/C/Program Files/erl7.1/usr/lib"

**Comment by fire** [comment]
If I remove those headers and libs I get:

```
$ PKG_CONFIG_PATH=/mingw64/lib/pkgconfig/  make
 C      esdl2.c
/c/w/esdl2/c_src/esdl2.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Copyright (c) 2014-2015, Loïc Hoguin <essen@ninenines.eu>
 ^
In file included from /c/w/esdl2/c_src/esdl2.h:254:0,
                 from /c/w/esdl2/c_src/esdl2.c:15:
/c/w/esdl2/c_src/nif_helpers.h:18:21: fatal error: erl_nif.h: No such file or directory
 #include "erl_nif.h"
                     ^
compilation terminated.
erlang.mk:5585: recipe for target '/c/w/esdl2/c_src/esdl2.o' failed
make: *** [/c/w/esdl2/c_src/esdl2.o] Error 1
```

**Comment by fire** [comment]
It's not an error with the Makefile.

**Comment by fire** [comment]
How do you have sdl2-config? It's not in the pacman repos you described.

**Comment by fire** [comment]
I just noticed I did not run "pacman --noconfirm -Syu". Will report back later.

**Comment by essen** [comment]
Yeah, I run into the same issue as @fire. It's the same issue I had before too.

@brainstormi Just to be sure I am installing the most recent OTP (same as you use). But I wonder, are you perhaps using the *32-bit* installation of Erlang? I am using the 64-bit one, and considering the error occurs with the __int64 type, maybe something is up with this...

**Comment by essen** [comment]
Hm guess not considering the installation directory.

**Comment by essen** [comment]
Found the issue!

**Comment by essen** [comment]
The key was in the "/mingw64/bin/gcc" binary, which is not the same as "gcc". The former works, the latter gives the result @fire had above. Next step is to fix Erlang.mk to do those things automatically, and then add the queue library to the project.

**Comment by brainstormi** [comment]
Essen, did you notice the stuttering when running the second part of the demo (4 big circles...) in windows?.

**Comment by essen** [comment]
It runs perfectly fine for me. I am not surprised there can be some slowdown though, as it's the most intensive part of the (completely unoptimized) demo, and I had noticed slowdowns on Linux when I originally wrote it.

Blame the poor programming on my part for that one.

**Comment by brainstormi** [comment]
Only subjective impressions here... Trying to analyze a bit the slowdowns in my windows, i see that the CPU overload only is affecting to 1 core, i suppose due to the serialization in the nif threading... rest of cpus, sit there doing nothing; but more corious thing is that the slowdowns appears randomly before big CPU spikes.

**Comment by essen** [comment]
It's not on the NIF side that the CPU is used this much. The demo has a single Erlang process doing a lot of math calculations to update many elements on the screen. These kinds of calculations are generally slow in Erlang, and here they're also not optimized at all.

In other words, it's not esdl2, it's the demo.

**Comment by essen** [comment]
I just pushed a commit with the Erlang.mk related changes. Can you check that it still works for you?

The only thing you should do to make it work out of the box now is add the separate queue library and point the two files that include it. No Makefile change should now be required.

After confirmation this works, I will move on to including the queue library (or finding a package that has it) and we should be good on Windows (minus crash at the end).

**Comment by brainstormi** [comment]
It's working properly... after making a distclean and dropping hacks like cc link to gcc, it compiles cleanly updating erlang.mk, generating the nif with .dll extension instead of .so.

**Comment by essen** [comment]
Very nice, thanks!

**Comment by essen** [comment]
I have pushed the commit adding queue.h in the repository. The esdl2 project should now work out of the box. Please confirm. I will myself test if nothing broke on Linux and OSX.

Thanks!

**Comment by essen** [comment]
Looks like I broke something on Linux. :-)

**Comment by essen** [comment]
I confirm both Windows and Linux work. OSX will take me a little more time to confirm.

**Comment by brainstormi** [comment]
I could test it on OSX environment tonight...

**Comment by essen** [comment]
I confirm it works on OSX also. If you want you can independently verify this, I'm always welcome to hearing it works for more than me. :-)

I will be closing the ticket now and finalize the patch in Erlang.mk itself (need some small doc changes).

Thanks for all the help!

**Comment by essen** [comment]
Erlang.mk master now includes the fixes.
