### ISSUE TITLE
seg fault when crashing in render step

### ISSUE THREAD

**Issue by hdiedrich** [ninenines/esdl2#4]
I think all my seg faults were caused by the root cause of this: when there is a crash during rendering, it results into a seg fault on my (vanilla) machine.

    cd examples/dot && ./start.sh
    Erlang/OTP 17 [erts-6.0] [source-07b8f44] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
    
    Eshell V6.0  (abort with ^G)
    1> ./start.sh: line 2: 64246 Segmentation fault: 11  erl +stbt db -pa ../../ebin -eval     "dot:run()."
                       make: *** [dot] Error 139
                                                air:esdl2 hd$ 

This is the source I used. I only changed render/1:

    -module(dot).
    -export([run/0]).
    
    run() ->
            spawn_opt(fun init/0, [{scheduler, 0}]).
    
    init() ->
            %% setup sdl, window and renderer
            ok = sdl:start([video]),
            ok = sdl:stop_on_exit(),
            {ok, Window} = sdl_window:create("Dot", 10, 10, 500, 500, []),
            {ok, Renderer} = sdl_renderer:create(Window, -1, [accelerated, present_vsync]),
            %% start animaton
            loop(#{window=>Window, renderer=>Renderer, t=>0}).
    
    %% animation loop
    loop(State) ->
            events_loop(),
            loop(render(State)).
    
    %% check for termination
    events_loop() ->
            case sdl_events:poll() of
                    false -> ok;
                    #{type:=quit} -> terminate();
                    _ -> events_loop()
            end.
    
    %% render one frame
    render(#{renderer:=Renderer, t:=T}=State) ->
            1/0,
            State#{t=>T + 1}.
    
    terminate() ->
            init:stop(),
            exit(normal).

**Comment by essen** [comment]
Closing as probably fixed.
